version: '3.8'
services:
  api:
    build:
      context: ./
    container_name: api
    environment:
      - NODE_ENV=dev
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
  db:
    image: postgres:latest
    container_name: db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=daphne

networks:
  nestjs_network:
    driver: bridge
